name: Remote Deploy on vServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            npm install tailwindcss @tailwindcss/cli
            cd /var/projects/nomade.samwilliam.de
            git pull origin main
            npm install
            npm run build
            chown -R www-data:www-data /var/projects/nomade.samwilliam.de
            npm run watch:css